### ISSUE TITLE
can't see attached file

### ISSUE THREAD

**Issue by ftakao2007** [joruri/joruri-mail#20]
正規表現で「HA[0-9]*\\.xls」にマッチするような名前のファイルを添付したメールを正常に開くことができませんでした。

デモ環境にて自分自身に上記のような名前の添付メールを送ったところ、件名に添付ファイルがある場合に表示されるクリップのアイコンは表示されるのですが、実際の添付ファイルは表示されませんでした。

また別途構築している検証環境でThunderbirdから「HA[0-9]*\\.xls」のような添付ファイル付きメールを送信し、それをJoruriMailで確認したところ「unknown encoding name - ibm424_ltr <ActionView::Template::Error>」というエラーが発生しました。

メールサーバに入り、メールのデータを「TEST.xls」のように正規表現にマッチしないものに直接編集するとJoruriMailで閲覧することができるようになりました。

---
■ before
Content-Type: application/vnd.ms-excel;
 name="HA1234.xls"
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
 filename="HA1234.xls"

■ after
Content-Type: application/vnd.ms-excel;
 name="TEST.xls"
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
 filename="TEST.xls"

---

こちらの現象についてまた何か分かりましたら追記いたします。

**Comment by syncsyncsynchalt** [comment]
mail gemへのパッチ `./lib/plugins/exts/mail/sanitizer.rb` の `adjust_encoding`  メソッドが
電文を壊してしまうのが直接的な原因のようです。外すと動きはするようになります。

` exts/mail` 下の実装が起こされた歴史的経緯を汲み取りながら
いまの mail 2.6.4 との整合性を取る形になるかとおもいます。。

**Comment by kanety** [comment]
v2-developブランチにて修正しました。
